# config.py

ADDIN_NAME = "CylinderGenerator"
COMPANY_NAME = "JuanOlaya"

# Default Dimensions
DEFAULT_OUTER_DIAMETER = "40 mm"
DEFAULT_LENGTH = "120 mm"
DEFAULT_WALL_THICKNESS = "2.5 mm"

DEFAULT_BOSS_DIAMETER = "8 mm"
DEFAULT_BOSS_HEIGHT = "6 mm"

DEFAULT_INSERT_OUTER_DIAMETER = "4.5 mm"
DEFAULT_INSERT_HOLE_DIAMETER = "4.4 mm"

DEFAULT_SCREW_HOLE_DIAMETER = "3.3 mm"
DEFAULT_COUNTERBORE_DIAMETER = "5.8 mm"
DEFAULT_COUNTERBORE_DEPTH = "3 mm"

DEFAULT_CORNER_OFFSET = "8 mm"
DEFAULT_NUMBER_OF_BOSSES = "4"
DEFAULT_FILLET_RADIUS = "1 mm"
