const fs = require('fs');
const path = require('path');

function getGermanFormattedDate() {
    const date = new Date();
    try {
        const formatter = new Intl.DateTimeFormat('en-US', {
            timeZone: 'Europe/Berlin',
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
        });
        const parts = formatter.formatToParts(date);
        const partMap = {};
        parts.forEach(p => { partMap[p.type] = p.value; });
        
        const tzFormatter = new Intl.DateTimeFormat('en-US', {
            timeZone: 'Europe/Berlin',
            timeZoneName: 'longOffset'
        });
        const tzParts = tzFormatter.formatToParts(date);
        const tzOffsetPart = tzParts.find(p => p.type === 'timeZoneName');
        const tzOffset = tzOffsetPart ? tzOffsetPart.value : 'GMT+02:00';
        
        return `${partMap.year}-${partMap.month}-${partMap.day}  T_${partMap.hour}:${partMap.minute}:${partMap.second}  ${tzOffset}`;
    } catch (e) {
        const iso = date.toISOString();
        const datePart = iso.substring(0, 10);
        const timePart = iso.substring(11, 19); // Omit milliseconds
        return `${datePart}  T_${timePart}  GMT+00:00`;
    }
}

/**
 * Updates the verbs_index.json file with current group data
 */
function updateVerbsIndex() {
    const groupsDir = path.join(__dirname, 'json', 'groups');
    const allGroups = [];

    console.log('Updating verbs index...');

    // Level directories to scan
    const levels = ['A1_1', 'A1_2', 'A2_1', 'A2_2', 'B1_1', 'B2_1'];

    levels.forEach(level => {
        const levelDir = path.join(groupsDir, level);
        if (!fs.existsSync(levelDir)) {
            console.warn(`Warning: Level directory not found: ${levelDir}`);
            return;
        }

        const files = fs.readdirSync(levelDir).sort((a, b) => {
            const matchA = a.match(/_group_(\d+)\.json$/);
            const matchB = b.match(/_group_(\d+)\.json$/);
            const numA = matchA ? parseInt(matchA[1], 10) : 0;
            const numB = matchB ? parseInt(matchB[1], 10) : 0;
            return numA - numB;
        });
        files.forEach(file => {
            if (file.endsWith('.json') && file.includes('_group_')) {
                const filePath = path.join(levelDir, file);
                try {
                    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
                    allGroups.push({
                        level: data.level,
                        verbCount: data.verbs ? data.verbs.length : 0,
                        verbs: data.verbs || [],
                        groupNameGerman: data.germanName || data.theme || "Unbekannt",
                        groupNameSpanish: data.spanishName || ""
                    });
                } catch (error) {
                    console.error(`⚠ Error reading ${file}:`, error.message);
                }
            }
        });
    });

    // Calculate groupNumberPerLevel for each group
    const levelCounts = {};
    allGroups.forEach(group => {
        if (!levelCounts[group.level]) {
            levelCounts[group.level] = 0;
        }
        levelCounts[group.level]++;
        group.groupNumberPerLevel = levelCounts[group.level];
    });

    // Create index data
    const indexData = {
        _DEVELOPER_WARNING: "DO NOT EDIT THIS FILE DIRECTLY! The source of truth for verb groups is in the json/groups/ directory. To change groups, follow the instructions in HOW_TO_ADD_GROUPS.md: 1) Edit the JSON files in json/groups/. 2) Update script.js's physicalLevelMap. 3) Run 'node update_index.js'. 4) Run 'node sync_card_groups.js'. 5) Verify with 'node verify_inventory.js'.",
        lastUpdated: getGermanFormattedDate(),
        totalGroups: allGroups.length,
        totalVerbs: allGroups.reduce((sum, g) => sum + g.verbCount, 0),
        groups: allGroups
    };

    // Write index file
    const indexPath = path.join(__dirname, 'json', 'verbs_index.json');
    fs.writeFileSync(indexPath, JSON.stringify(indexData, null, 4) + '\n', 'utf8');

    console.log(`✓ Index updated: ${indexData.totalVerbs} verbs across ${allGroups.length} groups`);

    // Display level summary
    const levelSummary = {};
    allGroups.forEach(g => {
        if (!levelSummary[g.level]) {
            levelSummary[g.level] = { groups: 0, verbs: 0 };
        }
        levelSummary[g.level].groups++;
        levelSummary[g.level].verbs += g.verbCount;
    });

    console.log('\nSummary by level:');
    Object.entries(levelSummary).sort().forEach(([level, stats]) => {
        console.log(`  ${level}: ${stats.groups} groups, ${stats.verbs} verbs`);
    });
}

// Run if called directly
if (require.main === module) {
    updateVerbsIndex();
}

module.exports = { updateVerbsIndex };
